/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cell/{cell_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cell */
        get: operations["cell_api_cell__cell_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cell/{cell_id}/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cell Conversations */
        get: operations["cell_conversations_api_cell__cell_id__conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cells": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Cells */
        get: operations["cells_api_cells_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_api_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat Stream */
        post: operations["chat_stream_api_chat_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/conversation/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conversation */
        get: operations["conversation_api_conversation__conversation_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Candidate */
        Candidate: {
            /** Cell Id */
            cell_id: string;
            /** In Basin */
            in_basin?: boolean | null;
            /** Km To Label */
            km_to_label?: number | null;
            /** Known Share */
            known_share?: number | null;
            /** Label Name */
            label_name?: string | null;
            /** Label Tier */
            label_tier?: string | null;
            /** Lat */
            lat: number;
            /** Lon */
            lon: number;
            /** Score */
            score?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** CellConversations */
        CellConversations: {
            /** Cell Id */
            cell_id: string;
            /** Conversations */
            conversations: components["schemas"]["ConversationSummary"][];
        };
        /** Cells */
        Cells: {
            /** Cells */
            cells: components["schemas"]["Candidate"][];
        };
        /** ChatRequest */
        ChatRequest: {
            /**
             * Cell Id
             * @description looks like 0123_0045
             */
            cell_id: string;
            /** Conversation Id */
            conversation_id?: string | null;
            /** Question */
            question: string;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Cell Id */
            cell_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Cost Usd */
            cost_usd: number;
            turn: components["schemas"]["Turn"];
            /** Values */
            values: {
                [key: string]: components["schemas"]["Val"];
            };
        };
        /** Claim */
        Claim: {
            /** Claim No */
            claim_no?: number | null;
            /** Text */
            text: string;
            /** Value Ids */
            value_ids?: string[];
        } & {
            [key: string]: unknown;
        };
        /** ConversationRecord */
        ConversationRecord: {
            /** Backend */
            backend: string;
            /** Cell Id */
            cell_id: string;
            /** Conversation Id */
            conversation_id: string;
            /** Created At */
            created_at: string;
            /** Model */
            model: string;
            /** Turns */
            turns: components["schemas"]["StoredTurn"][];
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Backend */
            backend: string;
            /** Conversation Id */
            conversation_id: string;
            /** Cost Usd */
            cost_usd: number;
            /** Created At */
            created_at: string;
            /** Model */
            model: string;
            /** Turns */
            turns: number;
        };
        /** Evidence */
        Evidence: {
            /** Cell Id */
            cell_id: string;
            /** In Basin */
            in_basin?: boolean | null;
            /** Lat */
            lat?: number | null;
            /** Lon */
            lon?: number | null;
            /** Memos */
            memos: components["schemas"]["Memo"][];
            /** Parts */
            parts: {
                [key: string]: components["schemas"]["ToolResultOut"];
            };
            /** Values */
            values: {
                [key: string]: components["schemas"]["Val"];
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Backend */
            backend: string;
            /** Effort */
            effort: string;
            /** Model */
            model: string;
            /** Ok */
            ok: boolean;
        };
        /** Memo */
        Memo: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Created At */
            created_at: string;
            /** Memo Id */
            memo_id: string;
            /** Published */
            published: boolean;
            /** Role */
            role: string;
            /** Verdict */
            verdict?: string | null;
        };
        /** StoredTurn */
        StoredTurn: {
            /** Claims */
            claims: components["schemas"]["Claim"][];
            /** Cost Usd */
            cost_usd?: number | null;
            /** Created At */
            created_at: string;
            /** Duration S */
            duration_s?: number | null;
            /** Problems */
            problems: string[];
            /** Published */
            published: boolean;
            /** Question */
            question: string;
            /** Step */
            step: number;
            /** Text */
            text?: string | null;
            /** Tool Calls */
            tool_calls: components["schemas"]["ToolCall"][];
            /** Values */
            values: {
                [key: string]: components["schemas"]["Val"];
            };
        };
        /** ToolCall */
        ToolCall: {
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /** File */
            file?: string | null;
            /** Rows */
            rows?: number | null;
            /** Tool */
            tool: string;
            /** Values */
            values?: number | null;
        } & {
            [key: string]: unknown;
        };
        /** ToolResultOut */
        ToolResultOut: {
            /** Args */
            args: {
                [key: string]: unknown;
            };
            /**
             * Note
             * @default
             */
            note: string;
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
            /** Tool */
            tool: string;
            /** Values */
            values: {
                [key: string]: components["schemas"]["Val"];
            };
        };
        /** Turn */
        Turn: {
            /** Asked At */
            asked_at?: string | null;
            /**
             * Cannot Answer
             * @default false
             */
            cannot_answer: boolean;
            /** Caveats */
            caveats?: string[];
            /** Claims */
            claims?: components["schemas"]["Claim"][];
            /** Cost Usd */
            cost_usd?: number | null;
            /** Problems */
            problems?: string[];
            /** Published */
            published: boolean;
            /** Question */
            question: string;
            /** Text */
            text?: string | null;
            /** Tools Used */
            tools_used?: string[];
            /**
             * Usage Limited
             * @default false
             */
            usage_limited: boolean;
        } & {
            [key: string]: unknown;
        };
        /** Val */
        Val: {
            /** As Printed */
            as_printed?: string | null;
            /** Fmt */
            fmt?: string | null;
            /** Id */
            id: string;
            /** Kind */
            kind?: string | null;
            /** Note */
            note?: string | null;
            /** Unit */
            unit?: string | null;
            /** Unit As Printed */
            unit_as_printed?: string | null;
            /** Value */
            value?: number | string | boolean | null;
        } & {
            [key: string]: unknown;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    cell_api_cell__cell_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Evidence"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cell_conversations_api_cell__cell_id__conversations_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CellConversations"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cells_api_cells_get: {
        parameters: {
            query?: {
                limit?: number;
                model?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cells"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_api_chat_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_stream_api_chat_stream_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    conversation_api_conversation__conversation_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationRecord"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
