"""`ue prospect table`: the data readiness table, written as Markdown.

Three tables, generated from the register and the live store rather than written by hand, so they cannot drift
from what the pipeline actually did: what we pull, what we compute from it, and what does not exist.
"""

from __future__ import annotations

import json
from typing import Any, Callable

from ..paths import PATHS
from ..store import connect
from .inventory import load as load_inventory
from .readiness import table as readiness_table

ACCESS = {
    "arcgis_rest": "ArcGIS REST query",
    "stac": "STAC search, windowed COG read",
    "internal": "this pipeline",
    "file": "file on disk",
}

OUT = PATHS.pipeline / "knowledge" / "data_readiness_table.md"


def _short_licence(name: str) -> str:
    if "Saskatchewan" in name:
        return "SK open"
    if "Copernicus" in name:
        return "Copernicus"
    if "USGS" in name:
        return "USGS public domain"
    return "none stated"


def _how(op: str, params: dict[str, Any]) -> str:
    """One plain sentence per processing step, so the table reads without the source beside it."""
    radius_km = (params.get("radius_m") or 0) / 1000
    if op == "distance_to_lines":
        return "distance from the cell centre to the nearest line"
    if op == "line_density":
        return "line length clipped to the cell, per km2"
    if op == "point_stat":
        stat = {"max": "highest", "count": "number of", "mean": "mean", "p90": "90th percentile"}.get(
            str(params.get("stat")), str(params.get("stat"))
        )
        return f"{stat} {params.get('value_field')} among points within {radius_km:.0f} km"
    if op == "point_year":
        return f"earliest year from {params.get('date_field')} within {radius_km:.0f} km"
    if op == "idw":
        return (f"inverse-distance from the {params.get('k')} nearest observations, "
                f"null beyond {(params.get('max_m') or 0) / 1000:.0f} km")
    if op == "polygon_class":
        return f"{params.get('field_name')} of the polygon covering most of the cell"
    if op == "graphitic_host":
        return "bedrock lithology text matched against graphite and pelite words"
    if op == "polygon_overlap_count":
        return "how many footprints cover the cell"
    if op == "raster_zonal":
        return "class fractions or statistics over the pixels falling in the cell"
    return op


def build(log: Callable[[str], None] = print) -> str:
    inv = load_inventory()
    cov = {str(r["feature_key"]): r for _, r in readiness_table().iterrows()}

    con = connect(read_only=True)
    try:
        ops = {
            k: (o, json.loads(p or "{}"))
            for k, o, p in con.execute(
                "select feature_key, any_value(op), any_value(params) from derived.cell_feature group by 1"
            ).fetchall()
        }
        scenes = con.execute(
            "select collection, count(*), min(datetime), max(datetime) from native.scene group by 1 order by 1"
        ).fetchall()
    finally:
        con.close()

    lines: list[str] = [
        "# Data readiness: sources, processing, features",
        "",
        "Generated by `ue prospect table` from `knowledge/data_inventory.toml` and the live store. Every number",
        "here is what the pipeline actually produced, not a plan.",
        "",
        "## 1. Sources: what we pull",
        "",
        "| source | records | how it arrives | licence | role | bears on |",
        "|---|---:|---|---|---|---|",
    ]
    for s in inv.sources:
        n = f"{s.record_count:,}" if s.record_count else ("raster" if s.access == "stac" else "-")
        mark = "" if s.verified else " *(unverified)*"
        lines.append(
            f"| {s.title}{mark} | {n} | {ACCESS.get(s.access, s.access)} | {_short_licence(s.licence.name)} "
            f"| {s.role} | {s.bears_on} |"
        )

    lines += [
        "",
        "## 2. Features: what we compute from them",
        "",
        "Coverage is the share of grid cells that carry a real observation. A cell with no observation holds",
        "null, never zero, and *thin* marks a feature too sparse to carry a basin-wide model on its own.",
        "",
        "| feature | from | how it is computed | unit | coverage | kind |",
        "|---|---|---|---|---:|---|",
    ]
    rows = sorted(cov.values(), key=lambda r: (bool(r["is_effort"]), -float(r["coverage"] or 0)))
    for r in rows:
        key = str(r["feature_key"])
        op, params = ops.get(key, ("", {}))
        src = ", ".join(json.loads(r["source_keys"]) if isinstance(r["source_keys"], str) else [])
        thin = " *thin*" if r["thin"] else ""
        unit = r["unit"] if r["unit"] == r["unit"] and r["unit"] else "-"
        kind = "effort" if r["is_effort"] else str(r["bears_on"])
        lines.append(
            f"| `{key}` | {src} | {_how(op, params)} | {unit} | {float(r['coverage'] or 0):.0%}{thin} | {kind} |"
        )

    if scenes:
        lines += ["", "## 3. Imagery actually read", "",
                  "| collection | scenes | earliest | latest |", "|---|---:|---|---|"]
        for coll, n, lo, hi in scenes:
            lines.append(f"| {coll} | {n} | {str(lo)[:10]} | {str(hi)[:10]} |")

    lines += ["", "## 4. Gaps: what does not exist publicly", "",
              "| gap | status | why it matters |", "|---|---|---|"]
    for g in inv.gaps:
        lines.append(f"| {g.title} | {g.status.replace('_', ' ')} | {g.why_it_matters} |")

    text = "\n".join(lines) + "\n"
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(text)
    log(f"  wrote {OUT.relative_to(PATHS.root)} ({len(rows)} features, {len(inv.sources)} sources)")
    return text
