"""`ue bench`: build, audit and show a benchmark version; compute the out-of-fold score table.

Registered on the main CLI as `app.add_typer(bench_app, name="bench")`. Nothing here computes: each command
calls one function of the package and prints what it returns.
"""

from __future__ import annotations

import typer

bench_app = typer.Typer(no_args_is_help=True, help="UraniumBench: frozen, anonymised benchmark cells.")


def _plain(fn, *args, **kwargs):
    """A benchmark or dataset that is not on disk is one line naming what builds it, and exit 2, never a
    traceback: a public clone has neither the dataset nor the built packs."""
    try:
        return fn(*args, **kwargs)
    except FileNotFoundError as err:
        typer.echo(f"  {err}", err=True)
        raise typer.Exit(2) from err


@bench_app.command("build")
def build_cmd(version: str = typer.Option("v1", "--version", help="spec under configs/bench/<version>.toml")) -> None:
    """Write data/bench/<version>/ from the spec and the store (resumable; the store is read only)."""
    from .build import build

    m = _plain(build, version, log=typer.echo)
    typer.echo(f"built {version}: {m['counts']['cells']} cells, {len(m['files'])} files hashed")


@bench_app.command("audit")
def audit_cmd(version: str = typer.Option("v1", "--version")) -> None:
    """Re-hash every file and scan every pack and passage for anything that places or names the ground."""
    from .build import audit

    problems = _plain(audit, version)
    for p in problems:
        typer.echo(f"  {p}")
    typer.echo(f"{version}: {'clean' if not problems else f'{len(problems)} problem(s)'}")
    raise typer.Exit(1 if problems else 0)


@bench_app.command("show")
def show_cmd(version: str = typer.Option("v1", "--version")) -> None:
    """Counts per stratum and split, shortfalls, and what was hashed."""
    from .build import show

    _plain(show, version, log=typer.echo)


@bench_app.command("oof-scores")
def oof_scores_cmd(seed: int = typer.Option(0, "--seed"),
                   write: bool = typer.Option(False, "--write/--no-write",
                                              help="write derived.cell_score_oof (otherwise print a summary)")) -> None:
    """Out-of-fold learned, effort and criteria scores for every scorable cell under 30 km spatial folds."""
    from ..store import connect
    from .oof import oof_scores, write_oof_scores

    df = oof_scores(seed)
    for model, g in df.groupby("model"):
        ok = g["score"].notna()
        typer.echo(f"  {model:9} {int(ok.sum()):,} scored of {len(g):,}  mean {g['score'].mean():.3f}")
    if write:
        con = connect()
        try:
            n = write_oof_scores(df, con, run_id=f"bench-oof-seed{seed}")
        finally:
            con.close()
        typer.echo(f"wrote {n:,} rows to derived.cell_score_oof")
    else:
        typer.echo("not written (pass --write)")


# ---------------------------------------------------------------- the interface track

interface_app = typer.Typer(no_args_is_help=True,
                            help="UraniumBench, interface track: tiers 1 and 3, generated by code, gold computed by code.")
bench_app.add_typer(interface_app, name="interface")


@interface_app.command("build")
def interface_build_cmd(version: str = typer.Option("v1", "--version",
                                                    help="spec under configs/bench/interface-<version>.toml")) -> None:
    """Write interface/<version>/ under the dataset directory (knowledge/bench/, or UE_BENCH_KNOWLEDGE_DIR) from the
    spec, the analyst benchmark and the store (read only)."""
    from .interface.build import build

    m = _plain(build, version, log=typer.echo)
    c = m["counts"]
    typer.echo(f"built interface {version}: tier 1 {c['tier1']['items']} items, tier 3 {c['tier3']['items']} items, "
               f"content {m['content_sha256'][:12]}")


@interface_app.command("audit")
def interface_audit_cmd(version: str = typer.Option("v1", "--version")) -> None:
    """Re-hash the tier files and regenerate every item from its recorded choice against the store."""
    from .interface.build import audit

    problems = _plain(audit, version)
    for p in problems:
        typer.echo(f"  {p}")
    typer.echo(f"interface {version}: {'clean' if not problems else f'{len(problems)} problem(s)'}")
    raise typer.Exit(1 if problems else 0)


@interface_app.command("show")
def interface_show_cmd(version: str = typer.Option("v1", "--version")) -> None:
    """Counts by tier, kind, stratum, reason and source; shortfalls; the hashes."""
    from .interface.build import show

    _plain(show, version, log=typer.echo)


@bench_app.command("leak")
def leak_cmd(version: str = typer.Option("v3", "--version")) -> None:
    """Can the passages alone rank the cells? Text-only and count-only models out of fold; no model call."""
    from .leak import audit, write

    result = audit(version)
    path = write(version, result)
    for view in ("redacted", "raw"):
        r = result.get(view) or {}
        if "pr_auc" in r:
            typer.echo(f"  {view:<9} text-only PR-AUC {r['pr_auc']:.3f} [{r['pr_auc_ci'][0]:.3f}, "
                       f"{r['pr_auc_ci'][1]:.3f}]  ROC {r['roc_auc']:.3f}  on {r['cells_with_text']} cells with text")
            typer.echo(f"            toward positive: {', '.join(r['toward_positive'][:12])}")
    c = result["count_only"]
    typer.echo(f"  count-only PR-AUC {c['pr_auc_passages']:.3f} (passages), {c['pr_auc_chars']:.3f} (characters); "
               f"base rate {result['base_rate']:.3f}")
    typer.echo(f"  wrote {path}")


@bench_app.command("recognise")
def recognise_cmd(
    version: str = typer.Option("v3", "--version"),
    backend: str = typer.Option("claude", "--backend", help="claude (the subscription CLI) or auto"),
    budget_usd: float = typer.Option(30.0, "--budget-usd"),
    workers: int = typer.Option(3, "--workers"),
) -> None:
    """Ask, cell by cell, which ground the redacted passages describe; score the guesses against the names near
    each cell. Exits 75 on a usage limit (resumable)."""
    import json

    from ..analyst.score import out_dir
    from ..backends.base import UsageLimitReached
    from .recognise import EFFORT, MODEL, run

    if backend == "claude":
        from ..backends.claude_cli import ClaudeCliBackend

        inner = ClaudeCliBackend(timeout_s=600, max_budget_usd=0.50)
    else:
        from ..backends.router import api_first

        inner = api_first(timeout_s=600)
    path = out_dir(version) / "recognise.jsonl"
    typer.echo(f"  recognition probe on {version}: {MODEL} at {EFFORT}, budget ${budget_usd:.2f}")
    try:
        result = run(version, inner, budget_usd, path, workers=workers, log=typer.echo)
    except UsageLimitReached as err:
        typer.echo(f"  usage limit: {err}")
        raise typer.Exit(75) from err
    (out_dir(version) / "recognise.json").write_text(json.dumps(result, indent=1) + "\n")
    for stratum, s in sorted(result["by_stratum"].items()):
        typer.echo(f"  {stratum:<11} {s['cells']:>4} cells, said recognised {s['said_recognised']}, "
                   f"named correctly {s['named_correctly']}")
    typer.echo(f"  cost ${result['cost_usd']:.2f}")


@bench_app.command("oof-seeds")
def oof_seeds_cmd(version: str = typer.Option("v3", "--version"), seeds: int = typer.Option(5, "--seeds")) -> None:
    """The fitted models' out-of-fold scores for a benchmark's cells under several fold draws, averaged in the
    table as `<model>-avg<N>`: the pre-registered comparison, since one draw moves PR-AUC by 0.02 to 0.05."""
    from .oof import SEEDS_FILE, seed_scores

    table = seed_scores(version, n_seeds=seeds, log=typer.echo)
    typer.echo(f"  wrote {len(table):,} rows to data/bench/{version}/{SEEDS_FILE}")


@bench_app.command("pilot")
def pilot_cmd(version: str = typer.Option("v3", "--version")) -> None:
    """Draw the pilot's cells by the pre-registered rule and write them beside the results."""
    from .pilot import draw, write

    got = draw(version)
    path = write(version, got)
    typer.echo(f"  {len(got['cells'])} cells ({got['eligible']}): {','.join(got['cells'])}")
    typer.echo(f"  wrote {path}")
